### ISSUE TITLE
Question to "php-signal"

### ISSUE THREAD

**Issue by CONOVA24** [Tsjippy/sim-plugin#23]
Hi Tsjippy, sorry to write you here but I found no other way to contact you. 
I would like to try your php-signal wrapper but I can't install it with "composer require Tsjippy/php-signal" since composer tells me that there is no package with that name. Am I doing something wrong? And could you maybe tell me how I can load it?
Thanks so much!

**Comment by Tsjippy** [comment]
Ah sorry, I should remove that line as I have not added it to composer.

you can just download the files, require them in your project
